################################################################################
# FILE 01: DATA PREPARATION AND VECTOR SPACE CONSTRUCTION
# ============================================================================
# Description: This script constitutes the empirical foundation of the study.
#              In it, we retrieve, clean, and transform raw data into
#             algebraic structures we can use (Matrices X, Vectors y).
#
# Methodology:
# 1. Extraction: Adjusted Prices (Yahoo Finance) and Risk Factors (Fama-French)
# 2. Transformation: Calculation of Logarithmic Returns (Log-Returns)
#    Property: r_t = ln(P_t) - ln(P_{t-1}). For temporal additivity
# 3. Alignment: Strict temporal join (Inner Join) for matrix consistency
# 4. Excess Return: Subtraction of the Risk-Free Rate
#    Model: R_{excess} = R_{asset} - R_{f}
################################################################################

# ============================================================================
# 1. LIBRARY LOADING AND CONFIGURATION
# ============================================================================
# tidyverse: Data manipulation (dplyr, tidyr, ggplot2)
# quantmod: API interface for financial data (Yahoo Finance)
# lubridate: Robust date management
# janitor : Column name cleaning

if (!require("tidyverse")) install.packages("tidyverse")
if (!require("quantmod")) install.packages("quantmod")
if (!require("lubridate")) install.packages("lubridate")
if (!require("janitor")) install.packages("janitor")

library(tidyverse)
library(quantmod)
library(lubridate)
library(janitor)

# ============================================================================
# 2. DEFINITION OF THE INVESTMENT UNIVERSE
# ============================================================================
# We select of 20 major tech assets to capture sector dynamics
# and test model robustness against correlation

tickers <- c("NVDA", "AAPL", "MSFT", "AVGO", "AMZN", 
             "GOOGL", "GOOG", "TSLA", "META", "NFLX", 
             "PLTR", "COST", "AMD", "CSCO", "ORCL", 
             "WMT", "JPM", "BRK-B", "MU", "QCOM")

# Analysis period: 10/2020-10/2025
# Includes the COVID-19 crisis, the 2021 recovery, and the 2023-24 AI boom
start_date <- "2020-10-01"
end_date <- Sys.Date()

cat(sprintf("Initializing extraction for %d assets...\n", length(tickers)))

# ============================================================================
# 3. MARKET DATA EXTRACTION (YAHOO FINANCE)
# ============================================================================
# Using `getSymbols` to retrieve OHLCV time series
# We only keep the Adjusted Close price which integrates
# dividends and splits (going to be used for total return calculation)

stock_data_list <- list()

for (ticker in tickers) {
  tryCatch({
    # API Call
    df_xts <- getSymbols(ticker, src = "yahoo", from = start_date, to = end_date, auto.assign = FALSE)
    
    # Conversion xts -> tibble for tidy manipulation
    df <- data.frame(date = index(df_xts), coredata(df_xts)) %>%
      as_tibble() %>%
      clean_names() %>%
      select(date, adjusted = ends_with("adjusted")) %>%
      mutate(ticker = ticker)
    
    stock_data_list[[ticker]] <- df
    cat(sprintf("✓ Success: %s\n", ticker))
  }, error = function(e) {
    cat(sprintf("⚠ Error for %s: %s\n", ticker, e$message))
  })
}

# Aggregation into a single DataFrame (Long Format)
raw_stocks <- bind_rows(stock_data_list)

# ============================================================================
# 4. CALCULATION OF LOGARITHMIC RETURNS (LOG-RETURNS)
# ============================================================================
# Formula: r_t = ln(P_t / P_{t-1}) = ln(P_t) - ln(P_{t-1})
# Theoretical advantages:
# 1. Temporal additivity: r_{0->T} = sum(r_t)
# 2. Symmetry and better approximation of normality than arithmetic returns
# 3. Numerical stability for small movements

returns_df <- raw_stocks %>%
  group_by(ticker) %>%
  arrange(date) %>%
  mutate(
    log_return = c(NA, diff(log(adjusted))) # First difference of logs
  ) %>%
  drop_na() %>% # Removal of the first observation (NA generated by diff)
  ungroup()

# Pivot to Wide Format (Date x Ticker Matrix)
# Necessary for covariance and linear algebra calculations
returns_matrix_df <- returns_df %>%
  select(date, ticker, log_return) %>%
  pivot_wider(names_from = ticker, values_from = log_return) %>%
  drop_na() # Removal of incomplete rows (strict temporal alignment)

cat("\nDimensions of the returns matrix:\n")
print(dim(returns_matrix_df))

# ============================================================================
# 5. INTEGRATION OF RISK FACTORS (FAMA-FRENCH)
# ============================================================================
# 3-Factor Model:
# 1. Mkt-RF: Market Excess Return (Systematic Risk)
# 2. SMB (Small Minus Big): Size Effect
# 3. HML (High Minus Low): Value Effec.
# Source: Kenneth R. French Data Library

ff_url <- "https://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/F-F_Research_Data_Factors_daily_CSV.zip"
ff_zip <- "data-raw/FF_Factors.zip"
ff_csv <- "data-raw/F-F_Research_Data_Factors_daily.CSV"

if (!file.exists("data-raw")) dir.create("data-raw")

# Conditional download (avoids re-downloading on each run)
if (!file.exists(ff_zip)) {
  cat("Downloading Fama-French factors...\n")
  download.file(ff_url, ff_zip, mode = "wb")
}

# Extraction and Reading
unzip(ff_zip, exdir = "data-raw")

# Specific cleaning for K. French CSV format (Skip header, parsing dates)
ff_raw <- read_csv(ff_csv, skip = 4, col_types = cols()) %>%
  rename(date = 1) %>%
  mutate(date = ymd(date)) %>%
  drop_na(date) %>%
  select(date, Mkt_RF = `Mkt-RF`, SMB, HML, RF) %>%
  mutate(across(c(Mkt_RF, SMB, HML, RF), ~ . / 100)) # Conversion % -> Decimal

# ============================================================================
# 6. CONSTRUCTION OF THE FINAL DATA SPACE
# ============================================================================
# Merging asset returns and exogenous factors
# Calculation of Excess Returns for each asset: y = R_i - R_f
# Standard dependent variable in asset pricing (CAPM, APT)

final_data <- returns_matrix_df %>%
  inner_join(ff_raw, by = "date")

# Transformation into Excess Return
for (ticker in tickers) {
  if(ticker %in% names(final_data)) {
    final_data[[ticker]] <- final_data[[ticker]] - final_data$RF
  }
}

# ============================================================================
# 7. SAVING AND PERSISTENCE
# ============================================================================
# Saving in RDS format (R native, preserves types) and CSV

if (!file.exists("data")) dir.create("data")

saveRDS(final_data, "data/clean_data.rds")
write_csv(final_data, "data/clean_data.csv")

cat("\nProcessing completed successfully.\n")
cat("File generated: data/clean_data.rds\n")
glimpse(final_data)

